name: Application Build Tests with MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install maven -y

    - name: Wait for MySQL
      run: |
        echo "Waiting for MySQL to start..."
        sleep 15

    - name: Build with Maven
      run: |
        mvn clean install -DskipTests
