name: Integration Tests with Maven and MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  integration-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL server to start..."
          sleep 15

      - name: Build SpringBoot Application with Maven
        run: |
          mvn spring-boot:run

      - name: Check MySQL Authentication
        run: |
          mysql --host=${MYSQL_DB_HOST} --port=${MYSQL_DB_PORT} --user=${MYSQL_DB_USERNAME} --password=${MYSQL_DB_PASSWORD} --execute='SHOW DATABASES;'
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}

      - name: Integration Test with Maven
        run: |
          mvn test -Dtest=UserIntegrationTest
        
