name: Integration Tests with Maven and MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  integration-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL server to start..."
          sleep 15

      - name: Run Integration Test with Maven
        run: |
          sudo mkdir /var/log/cloud/
          sudo chmod 750 /var/log/cloud/
          mvn test -Dtest=UserIntegrationTest
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}

