name: Build Packer on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  packer-merge-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build Application with Maven and Run Integration Test
        run: |
          cd /var/log/
          sudo mkdir cloud/
          ls -al 
          mvn clean install
          pwd
          mkdir cloud && cp target/csye6225-0.0.1-SNAPSHOT.jar cloud   
          cp cloud/*.jar packer
          cd packer && ls -al
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Format check Packer
        run: |
          cd packer
          packer fmt -check .
           if [ $? -ne 0 ]; then
            echo "Packer template was modified by 'packer fmt' command."
          fi

      - name: Validate Packer
        run: |
          cd packer
          packer validate .
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed."
          fi
        env:
          PKR_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          PKR_VAR_gcp_zone: ${{ secrets.GCP_ZONE }}
          PKR_VAR_ssh_username : ${{ secrets.PACKER_SSH_USERNAME }}
          PKR_VAR_source_image_family: ${{ secrets.SOURCE_IMAGE_FAMILY }}
          PKR_VAR_network: ${{ secrets.NETWORK }}
          PKR_VAR_image_storage_locations: ${{ secrets.IMAGE_STORAGE_LOCATIONS }}
          PKR_VAR_image_name: ${{ secrets.IMAGE_NAME }}
          PKR_VAR_image_family: ${{ secrets.IMAGE_FAMILY }}
          PKR_VAR_image_description : ${{ secrets.IMAGE_DESCRIPTION }}
          PKR_VAR_build_name : ${{ secrets.BUILD_NAME }}

      - name: Check if any job failed
        if: ${{ failure() }}
        run: exit 1

      - name: Build Packer
        run: |
          cd packer
          packer build .
        env:
          PKR_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          PKR_VAR_gcp_zone: ${{ secrets.GCP_ZONE }}
          PKR_VAR_ssh_username : ${{ secrets.PACKER_SSH_USERNAME }}
          PKR_VAR_source_image_family: ${{ secrets.SOURCE_IMAGE_FAMILY }}
          PKR_VAR_network: ${{ secrets.NETWORK }}
          PKR_VAR_image_storage_locations: ${{ secrets.IMAGE_STORAGE_LOCATIONS }}
          PKR_VAR_image_name: ${{ secrets.IMAGE_NAME }}
          PKR_VAR_image_family: ${{ secrets.IMAGE_FAMILY }}
          PKR_VAR_image_description : ${{ secrets.IMAGE_DESCRIPTION }}
          PKR_VAR_build_name : ${{ secrets.BUILD_NAME }}
            
