name: Build Packer on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  packer-merge-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Build Application with Maven and Run Integration Test
        run: |
          echo "LOG_FILE_PATH:  ${{ secrets.LOG_FILE_PATH }}" >> .env
          mvn clean install
          pwd
          mkdir cloud && cp target/csye6225-0.0.1-SNAPSHOT.jar cloud   
          cp cloud/*.jar packer
          cd packer && ls -al
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}
          GCP_PUBSUB_TOPIC_NAME: ${{ secrets.GCP_PUBSUB_TOPIC_NAME }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Format check Packer
        run: |
          cd packer
          packer fmt -check .
           if [ $? -ne 0 ]; then
            echo "Packer template was modified by 'packer fmt' command."
          fi

      - name: Validate Packer
        run: |
          cd packer
          packer validate .
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed."
          fi
        env:
          PKR_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          PKR_VAR_gcp_zone: ${{ secrets.GCP_ZONE }}
          PKR_VAR_ssh_username : ${{ secrets.PACKER_SSH_USERNAME }}
          PKR_VAR_source_image_family: ${{ secrets.SOURCE_IMAGE_FAMILY }}
          PKR_VAR_network: ${{ secrets.NETWORK }}
          PKR_VAR_image_storage_locations: ${{ secrets.IMAGE_STORAGE_LOCATIONS }}
          PKR_VAR_image_name: ${{ secrets.IMAGE_NAME }}
          PKR_VAR_image_family: ${{ secrets.IMAGE_FAMILY }}
          PKR_VAR_image_description : ${{ secrets.IMAGE_DESCRIPTION }}
          PKR_VAR_build_name : ${{ secrets.BUILD_NAME }}

      - name: Check if any job failed
        if: ${{ failure() }}
        run: exit 1

      - name: Build Packer
        run: |
          cd packer
          packer build .
        env:
          PKR_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          PKR_VAR_gcp_zone: ${{ secrets.GCP_ZONE }}
          PKR_VAR_ssh_username : ${{ secrets.PACKER_SSH_USERNAME }}
          PKR_VAR_source_image_family: ${{ secrets.SOURCE_IMAGE_FAMILY }}
          PKR_VAR_network: ${{ secrets.NETWORK }}
          PKR_VAR_image_storage_locations: ${{ secrets.IMAGE_STORAGE_LOCATIONS }}
          PKR_VAR_image_name: ${{ secrets.IMAGE_NAME }}
          PKR_VAR_image_family: ${{ secrets.IMAGE_FAMILY }}
          PKR_VAR_image_description : ${{ secrets.IMAGE_DESCRIPTION }}
          PKR_VAR_build_name : ${{ secrets.BUILD_NAME }}

      - name: Generate Random Number
        id: random_number
        run: echo "::set-output name=random_number::$RANDOM"

      - name: Create new Instance Template
        run: |
          random_number=${{ steps.random_number.outputs.random_number }}
          instance_template="test-instance-template-${random_number}"
          latest_image_name=$(gcloud compute images list --no-standard-images --format="table(NAME,CREATION_TIMESTAMP)" --sort-by="CREATION_TIMESTAMP" | tail -n 1)
          echo "$latest_image_name"
          latest_image_path="projects/${{ secrets.GCP_PROJECT_ID }}/global/images/$latest_image_name"
          
          gcloud compute instance-templates create $instance_template \
          --description="Test Instance Template Description" \
          --region=us-east1 \
          --instance-template-region=us-east1 \
          --machine-type=e2-small \
          --tags=http-server,webapp,allow-health-check \
          --labels=environment=dev \
          --image=$latest_image_path \
          --boot-disk-auto-delete \
          --boot-disk-type=pd-balanced \
          --boot-disk-size=20 \
          --network-interface=subnet=projects/csye6225-414009/regions/us-east1/subnetworks/csye6225-dev-vpc-webapp,network=projects/csye6225-414009/global/networks/csye6225-dev-vpc,network-tier=PREMIUM \
          --service-account=vm-service-account@csye6225-414009.iam.gserviceaccount.com \
          --boot-disk-kms-key=projects/${{ secrets.GCP_PROJECT_ID }}/locations/us-east1/keyRings/my-key-ring-1/cryptoKeys/vm-crypto-key \
          --metadata=startup-script="#! /bin/bash
          echo 'Startup script'
          cd /opt/cloud
          echo 'MYSQL_DB_USERNAME=${{ secrets.MYSQL_DB_USERNAME }}' >> .env
          echo 'MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}' >> .env
          echo 'MYSQL_DB_DATABASE=${{ secrets.MYSQL_DB_DATABASE }}' >> .env
          echo 'MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}' >> .env
          echo 'MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}' >> .env
          echo 'LOG_FILE_PATH=${{ secrets.LOG_FILE_PATH }}' >> .env
          echo 'GCP_PUBSUB_TOPIC_NAME={{ secrets.GCP_PUBSUB_TOPIC_NAME }}' >> .env
          echo 'GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}' >> .env"
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}
          GCP_PUBSUB_TOPIC_NAME: ${{ secrets.GCP_PUBSUB_TOPIC_NAME }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

