name: Build Packer on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  packer-merge-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build Application with Maven and Run Integration Test
        run: |
          mvn clean install
          pwd
          mkdir cloud && cp target/csye6225-0.0.1-SNAPSHOT.jar cloud   
          cp cloud/*.jar packer
          cd packer && ls -al
        env:
          MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
          MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
          MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
          MYSQL_DB_PORT: ${{ secrets.MYSQL_DB_PORT }}

      - name: Create .env file
        run: |
          echo "MYSQL_DB_USERNAME=${{ secrets.MYSQL_DB_USERNAME }}" >> .env
          echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> .env
          echo "MYSQL_DB_DATABASE=${{ secrets.MYSQL_DB_DATABASE }}" >> .env
          echo "MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}" >> .env
          echo "MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> .env
          cat .env
          cp .env packer
          cd packer && ls -al

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: '1.8.6'

      - name: Initialize Packer
        run: |
          cd packer
          sudo packer init .

      - name: Format check Packer
        run: |
          cd packer
          sudo packer fmt -check .

      - name: Validate Packer
        run: |
          cd packer
          sudo packer validate .

      - name: Build Packer
        run: |
          cd packer
          sudo packer build .
            
